-- Add body_improved field to project_emails table
ALTER TABLE public.project_emails 
ADD COLUMN body_improved TEXT;

-- Add index for better query performance on improved emails
CREATE INDEX idx_project_emails_body_improved 
ON public.project_emails(project_id, body_improved) 
WHERE body_improved IS NOT NULL;

-- Add comment
COMMENT ON COLUMN public.project_emails.body_improved IS 'Improved/branded email body generated by Branding Britta workflow';