// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fttdfvnhghbgtawkslau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dGRmdm5oZ2hiZ3Rhd2tzbGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNTA2NTgsImV4cCI6MjA3NjgyNjY1OH0.6Wdk__nMLGVoSQN6dMHqM-EP3SWJxHp3f81AOCGUry0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});